language: r
cache: packages
warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
sudo: required

apt_packages:
  - r-cran-rjava

before_install:
  - sudo $(which R) CMD javareconf
