language: r
cache: packages
warnings_are_errors: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
sudo: required

apt_packages:
  - r-cran-rjava
  - openjdk-11-jre-headless

before_install:
  - export JAVA_HOME=/usr/lib/jvm/default-java
  - export PATH=$PATH:$JAVA_HOME/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_HOME/lib/server
  - sudo /usr/local/lib/R CMD javareconf
